### ISSUE TITLE
Missing frames result in NoneType

### ISSUE THREAD

**Issue by IvRogoz** [MohamedAliRashad/FreeFaceMoCap#12]
Python: Traceback (most recent call last):
  File "C:\Users\nccwa\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Addon\Operators\captureFace.py", line 129, in modal
    self.one_euro_x = OneEuroFilter(self.frame_num, armature[:, 0])
TypeError: 'NoneType' object is not subscriptable

location: <unknown location>:-1

**Comment by JeraWolfe** [comment]
I'm getting this error too. Is there any information I can send you to help you fix it?

**Comment by JeraWolfe** [comment]
An excerpt from my console window. I am using Blender 3.1.2 (stable). Please advise if that is not the proper or correct version. Thank you. Also, if you want a tutorial in English, be happy to help you generate voice over for your video.
Cheers. Excellent work and proper respects, my friend.

Info: Successfully generated: "RIG-FFMoCap_Armature_001"
Python: Traceback (most recent call last):
  File "C:\Users\jeraw\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\FreeFaceMocap\Operators\generate_rig.py", line 34, in execute
    "WGTS_rig").name = get_name_of_object("WGTS_rig_")
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\jeraw\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\FreeFaceMocap\Operators\generate_rig.py", line 34, in execute
    "WGTS_rig").name = get_name_of_object("WGTS_rig_")
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

**Comment by MohamedAliRashad** [comment]
Working on it … sorry for the late guys I was just super busy the past few weeks
